### ISSUE TITLE
First run

### ISSUE THREAD

**Issue by ntphiep** [DangTinh422003/blog.dev-be#1]
How to run this project :)), please provide a README file @DangTinh422003

**Comment by DangTinh422003** [comment]
Đọc script trong file package.json đi

**Comment by ntphiep** [comment]
đéo hiểu :))

**Comment by ntphiep** [comment]
sao k có readme

**Comment by ntphiep** [comment]
có phải cái này k @DangTinh422003 
"nodemon --watch src --exec \"ts-node -r tsconfig-paths/register ./server.ts\"

**Comment by DangTinh422003** [comment]
pnpm install      pnpm run dev
